services:
  - type: web
    name: flickfrenzy-backend
    env: node
    buildCommand: npm install && cd src && npm install
    startCommand: cd src && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TMDB_API_KEY
        value: 20f841dd13926b7983444db8aa12c380
